---
permalink: /about/
---
= Über Softwerkbank

Der Name `Softwerkbank` ist aus den Worten _Software_ und _Werkbank_ zusammengesetzt. Die Softwareentwicklung wird in verschiedenen Communities als Handwerk angesehen. Ein*e Handwerker*in oder, in diesem Fall, ein*e Softwerker*in benötigt unterschiedliche Werkzeuge für die Umsetzung seiner*ihrer Projekte. Dabei wird als Arbeitsbereich meist eine Werkbank verwendet, die die verschiedenen Werkzeuge beherbergt. Hier soll es hauptsächlich um die verschiedenen Werkzeuge (Methoden, Technologien etc.) gehen, die bei der Softwareentwicklung eingesetzt werden.   

Bei meiner Arbeit in verschiedenen IT-Projekten liegt der Fokus zumeist nur auf die im Projekt verwendeten Technologien. 
Deshalb möchte ich diese Seite nutzen, um über den Tellerrand zu blicken und so Kenntnisse in Technologien und Methoden, mit denen ich sonst keine direkten Berührungspunkten habe, aufzubauen bzw. zu erweitern.
Das dabei erworbene Wissen möchte ich hier in Form von Blog-Beiträgen teilen und hoffe, dass das hier dokumentierte Wissen für den*die eine*n oder andere*n Softwareentwickler*in oder -architekt*in hilfreich ist.

== Über mich

Ich bin ein begeisterter Softwareentwickler und -architekt im Enterprise-Java-Umfeld. 
In meinem beruflichen Werdegang habe ich bei der Umsetzung verschiedener IT-Projekte in den Bereichen öffentliche Verwaltung, innere Sicherheit und Versicherungen mitgewirkt. 
Dabei ist es mein persönliches Ziel qualitativ hochwertige Softwaresysteme umzusetzen.
Neben den Bereichen der Softwarearchitektur und -entwicklung interessiere ich mich auch für agile Entwicklungsmethoden.

Nachfolgend möchte ich einige persönliche Präferenzen auflisten, damit ihr ein besseres Bild von mir habt.

* Lieber *Camping* als Hotel
* Lieber *Microsoft* statt Apple
* Lieber *zu Fuss* als mit Rad/Velo
