language: ruby
script: "./build.sh"
branches:
  only:
  - under-construction
rvm:
- 2.7.2
env:
  global:
    secure: DP/3hwAfALBqKUrX0UehhcHeZcQ1f0SKnk9iqEvFW2x8Yb5iOMzj9EqKVUg6i54myBghZyCvpchBRBcu8eqN3VS0cWo/HVWgX6c0vdVSyEZ/EpCmNMxo6A5QjCqJHl23fsje4bv+ueCmnG4gV4Y7A/Ls88QqFO8i84UErMys6US2N8z19KO9VZke6ROSy5Paoyi5qpaQ0qwa6C0xzvBqsSUBKl9KgjUfQ+vgS/oJBtkpyBMcrxXrAJNvUqGteGGC0q9MfP3LzRwXQnRS4/ZGzXPM3WLKx6H2gdVQUtIitQTr3r3LHP241gnGwnwNryq82gqw79GTuDKNW4M2C43TaEWSc/doE4Q5Ovt1RoGBPKHHhf0w4ol1Gdlpi0Btnbu/fJlzeCBy5J81WFWzKsNbJbKm4dm+K3dJ3CpMA8G2sPkcT6sW8Utpy3C22Wum7cfnUFOoAIkyDDjJAxKxZAWIpX5MS54iTq30/7SttbGXHDw3Vc0xc6DJVjmIUcc2KrPebzUtYElX4Ff0G6ERjEY1JIjK/yZXhsnMbJHFToAE3RK5YAoUwzUcIUE3uxplYOZtKmU8/HRzTWEfUFdSfzd9ejRmy3eH3/ZERpHl+TuqKbzXhcw68OxUKSokq+Yp76M3jkykq3QZhlco2fy8oBJmLoAxuTnSyitKucjtGTej8FA=
